export const dogs = [
   {
      Code: "p001",
      Name: "John",
      Photo: "/Photos/copy-of-09-pug_1704977095158.jpeg",
      Birthdate: "20/02/2019",
      Category: "Dog",
      Sex: "Male",
      Owner_Name: "John",
      Owner_Email: "John@email.com",
      Description: "childhood",
   },
   {
       Code: "p002",
       Name: "Mary",
       Photo: "/Photos/d21.jpg",
       Birthdate: "01/02/2019",
       Category: "Dog",
       Sex: "Male",
       Owner_Name: "Mary",
       Owner_Email: "Mary@example.com",
       Description: "reproductive age",
    },
    {
       Code: "p003",
       Name: "July",
       Photo: "/Photos/iq5115923fb9843f57ccdfd2a145c208a2.jpg",
       Birthdate: "09/02/2019",
       Category: "Dog",
       Sex: "Female", 
       Owner_Name: "Dooley",
       Owner_Email: "July@example.com",
       Description: "childhood",
    },
];
